export const FILTER_CONFIG = {
  bodyParts: [
    'back',
    'chest',
    'lower arms',
    'lower legs',
    'shoulders',
    'upper arms',
    'upper legs',
    'waist',
  ],
  equipment: [
    'band',
    'barbell',
    'body weight',
    'bosu ball',
    'cable',
    'dumbbell',
    'ez barbell',
    'kettlebell',
    'leverage machine',
    'medicine ball',
    'olympic barbell',
    'sled machine',
    'smith machine',
    'stability ball',
    'weighted',
  ],
  muscles: [
    'abductors',
    'abs',
    'biceps',
    'calves',
    'delts',
    'forearms',
    'glutes',
    'hamstrings',
    'lats',
    'pectorals',
    'quads',
    'traps',
    'triceps',
    'upper back',
  ],
};
